### PR TITLE
Basic app skeleton

### LINKED ISSUE #1: Create application skeleton.
Generated README should be filled with topic, name, description, developers.

### PR DESCRIPTION
**Pull request by neonowy**
* Generated basic Rails app.
* Added README

Closes #1.

### CODE REVIEW

**Comment by gotar** [comment]
drop Spring, replace sqlite with postgres

**Comment by taralalukasz** [comment]
+1

**Comment by pospieszynski** [comment]
@Ragnarson-Internship2016/mentors

**Comment by gotar** [comment]
👍 you can merge

**Pull request merged**
